# Generated by Django 2.1.5 on 2020-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
