# Generated by Django 2.1.5 on 2020-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0002_remove_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
