# Generated by Django 2.1.5 on 2020-03-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0003_auto_20200325_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dietary_requirments',
            field=models.CharField(choices=[('NA', 'None'), ('VA', 'Vegan'), ('VG', 'Vegatarian')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default='', max_length=128),
        ),
    ]
