# Generated by Django 2.1.5 on 2020-03-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0003_auto_20200314_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
