# Generated by Django 2.1.5 on 2020-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0004_auto_20200330_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('GLA', 'Glasgow'), ('EDI', 'Edinburgh'), ('MAN', 'Manchester')], default=None, max_length=3),
        ),
    ]
