# Generated by Django 2.1.5 on 2020-03-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0005_auto_20200314_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='bon_appetit_app.Menu'),
        ),
    ]
