# Generated by Django 2.1.5 on 2020-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0005_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('NON', 'None'), ('GLA', 'Glasgow'), ('EDI', 'Edinburgh'), ('MAN', 'Manchester')], default='NON', max_length=3),
        ),
    ]
