# Generated by Django 2.1.5 on 2020-03-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bon_appetit_app', '0006_auto_20200330_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
